# Generated by Django 2.1.3 on 2018-11-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
    ]
