# Generated by Django 2.1.3 on 2018-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20181117_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['the_order']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='position',
        ),
        migrations.AddField(
            model_name='lesson',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
