# Generated by Django 2.1.3 on 2018-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20181118_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_order']},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slide_order']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='the_order',
            new_name='lesson_order',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='position',
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
