# Generated by Django 2.1.3 on 2018-11-18 14:43

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20181118_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='lesson',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
    ]
