# Generated by Django 2.1.3 on 2018-11-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20181118_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
