# Generated by Django 2.1.3 on 2018-11-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20181125_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevent',
            name='action_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
