# Generated by Django 2.1.3 on 2018-11-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20181125_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningevent',
            name='element_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='element',
            field=models.FloatField(null=True),
        ),
    ]
