# Generated by Django 2.1.3 on 2018-11-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_auto_20181125_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningevent',
            old_name='element',
            new_name='slide',
        ),
    ]
