# Generated by Django 2.1.3 on 2018-11-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20181125_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningevent',
            name='lesson',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='slide',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
