# Generated by Django 2.1.3 on 2018-11-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_auto_20181125_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='next_available_lesson',
            new_name='next_lesson',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='next_available_slide',
            new_name='next_slide',
        ),
    ]
