# Generated by Django 2.1.3 on 2018-11-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20181126_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='next_lesson',
            new_name='active_lesson',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='next_slide',
            new_name='active_slide',
        ),
    ]
