# Generated by Django 2.1.3 on 2018-11-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_auto_20181127_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, null=True)),
                ('year_group', models.PositiveIntegerField(default=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=10, null=True)),
                ('section_class', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='lessons.Class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='lessons.School'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.School'),
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Section'),
        ),
    ]
