# Generated by Django 2.1.3 on 2018-12-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_auto_20181128_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('datetime', models.DateTimeField()),
                ('length', models.PositiveIntegerField()),
                ('ke_class', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='lessons.Class')),
            ],
        ),
    ]
