# Generated by Django 2.1.3 on 2018-12-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_ke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ke',
            name='ke_class',
        ),
        migrations.DeleteModel(
            name='Ke',
        ),
    ]
