# Generated by Django 2.1.3 on 2018-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_auto_20181202_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_weekday',
        ),
        migrations.AddField(
            model_name='class',
            name='active_lesson',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
