# Generated by Django 2.1.3 on 2018-12-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0026_auto_20181202_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('active_lesson', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='active_lesson',
            new_name='manual_unlock_lesson',
        ),
        migrations.AddField(
            model_name='class',
            name='manual_unlock_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ke',
            name='ke_class',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='lessons.Class'),
        ),
    ]
