# Generated by Django 2.1.3 on 2019-01-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_auto_20181203_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
