# Generated by Django 2.1.3 on 2019-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_slide_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
