# Generated by Django 2.1.3 on 2019-01-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_auto_20190116_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
