# Generated by Django 2.1.3 on 2019-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0033_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
